Fm/features/add comments (check after images PR!!!)
ClassTimes/classtimes-server pull request #36
Opened 2021-04-30 18:47 UTC by frankmangone

2021-05-01 23:58 UTC, gastonmorixe commented
@frankmangone changeed the base of this PR to the images one

2021-05-02 00:00 UTC, gastonmorixe commented on src/entities/calendarEvent/calendarEvent.service.ts
>      const conditions: TListCondition[] = []
I'd name it just `TConditions`

2021-05-02 00:09 UTC, gastonmorixe requested changes
Awesome u r killing it @frankmangone  :) requested some changes then LGTM

2021-05-02 00:09 UTC, gastonmorixe commented on src/entities/comment/comment.model.ts
> +import { User } from '../user/user.model'
add an empty line

2021-05-02 00:09 UTC, gastonmorixe commented on src/entities/comment/comment.model.ts
> +import * as Utils from '../../utils/Model'
group this line with line 6

2021-05-02 00:09 UTC, gastonmorixe commented on src/entities/comment/comment.model.ts
> +  content: string
add a validation of min length 2 chars using `class-validator` deco

2021-05-02 00:09 UTC, gastonmorixe commented on src/entities/discussion/discussion.inputs.ts
> +@GQL.InputType()
add empty line

2021-05-02 00:09 UTC, gastonmorixe commented on src/entities/discussion/discussion.model.ts
> +  @GQL.Field(() => String, { nullable: true })
why is this nullable?

2021-05-02 00:09 UTC, gastonmorixe commented on src/entities/discussion/discussion.model.ts
> +  @GQL.Field(() => String, { nullable: true })
why is it nullable? may you make it false and add a validation of at lease 2 chars?

2021-05-02 00:09 UTC, gastonmorixe commented on src/entities/discussion/discussion.model.ts
> +  @GQL.Field(() => String, { nullable: true })
may you make it false and add a validation of at lease 2 chars?

2021-05-02 00:09 UTC, gastonmorixe commented on src/entities/discussion/discussion.model.ts
> +    default: [],
why setting a default?

2021-05-02 00:09 UTC, gastonmorixe commented on src/entities/discussion/discussion.module.ts
> +    // {
you can remove this

2021-06-11 13:16 UTC, frankmangone commented on src/entities/discussion/discussion.model.ts
> +    default: [],
why not?

2021-06-11 13:20 UTC, merged